### ISSUE TITLE
Add click / hover to expand content

### ISSUE THREAD

**Issue by liy4502** [liy4502/KW_ACU#4]
Hover or click to expand more items

**Comment by dchopra001** [comment]
Can you give an example? Not sure what you mean here.

**Comment by liy4502** [comment]
To expand on this issue, when an information page is presented to the user, there are a list of items which contain hyperlinks that are hidden to avoid clustering the page under a main heading. When the user hovers over this heading(or description), it highlights, once clicked, it expands the list of items. For example, the heading "Fruits" contains a list of "apple","oranges","strawberry" which hyperlinks to their respective wikipedia pages to describe what they are. when the user hovers over "Fruits", it highlights it, and when clicked it expands the list of fruits

**Comment by liy4502** [comment]
I used JQuery click show on a button to do this. I use the slow animation so transition is smooth. Scripts are at the bottom of the page for the click show, list of elements are initially set as hidden.
